Add A11y review labels
canonical/labels pull request #11
Opened 2022-06-06 07:49 UTC by anthonydillon

## Done
Added the "Review: A11y" labels to the review set to indicate that the author of the change would like someone to perform an A11y specific review of it.

2022-06-15 16:16 UTC, petesfrench commented on labels.json
> +  { "name": "Review: Ally -1", "color": "#c7162b" },
```suggestion
  { "name": "Review: A11y -1", "color": "#c7162b" },
```

2022-06-15 16:18 UTC, petesfrench requested changes
Just a little spelling change

2022-06-22 12:04 UTC, anthonydillon commented
Sorry missed this @petesfrench, can you update the label. I thought you were reviewing it still.

2022-06-22 12:05 UTC, anthonydillon reviewed
@petesfrench ready for another review

2022-06-22 12:05 UTC, anthonydillon commented on labels.json
> +  { "name": "Review: Ally -1", "color": "#c7162b" },
Good catch!

2022-06-22 12:11 UTC, petesfrench approved these changes
LGTM! I will make sure to updated the label next time

2022-06-23 09:56 UTC, merged